// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace Core.Data.Entities
{
    public partial class BlogTagMapping
    {
        [Required]
        public int BlogId { get; set; }

        [Required]
        public int BlogTagId { get; set; }

        public Blog Blog { get; set; }
        public BlogTag BlogTag { get; set; }
    }
}