// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace Core.Data.Entities
{
    public partial class BlogTag
    {
        public BlogTag()
        {
            BlogTagMapping = new HashSet<BlogTagMapping>();
        }

        [Required]
        public Guid Id { get; set; }

        [Required]
        public Guid Name { get; set; }

        [Required]
        public string HexColorCode { get; set; }

        [Required]
        public DateTime CreateTime { get; set; }

        [Required]
        public string CreateUserId { get; set; }

        public virtual ICollection<BlogTagMapping> BlogTagMapping { get; set; }
    }
}