// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace Core
{
    public partial class Menu
    {
        public Menu()
        {
            RoleMenu = new HashSet<RoleMenu>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(10)]
        public string Name { get; set; }
        public int ParentId { get; set; }
        [Required]
        public bool? IsDisable { get; set; }

        [InverseProperty("Meun")]
        public virtual ICollection<RoleMenu> RoleMenu { get; set; }
    }
}