// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace Core
{
    public partial class Menu
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(10)]
        public string Name { get; set; }
        public int ParentId { get; set; }
        [Required]
        [StringLength(10)]
        public string Area { get; set; }
        [Required]
        [StringLength(20)]
        public string Controller { get; set; }
        [Required]
        [StringLength(20)]
        public string Action { get; set; }
        [Required]
        [StringLength(50)]
        public string Icon { get; set; }
        [Required]
        public bool IsDisable { get; set; }

        [Required]
        public int Sort { get; set; }

        [InverseProperty("Meun")]
        public virtual ICollection<RoleMenu> RoleMenu { get; set; }
    }
}