// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace Core.Data.Entities
{
    public partial class RoleMenu
    {
        [Key]
        public int RoleId { get; set; }
        [Key]
        public int MeunId { get; set; }

        [ForeignKey(nameof(MeunId))]
        [InverseProperty(nameof(Menu.RoleMenu))]
        public virtual Menu Meun { get; set; }
        [ForeignKey(nameof(RoleId))]
        [InverseProperty("RoleMenu")]
        public virtual Role Role { get; set; }
    }
}